Разметила главную страницу
htmlacademy-adaptive/161553-mishka-23 pull request #2
Opened 2021-07-25 20:32 UTC by IreneMMM

2021-08-01 20:17 UTC, Manyaka requested changes

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +            <td>Цвет:</td>
аналогично поправь дальше

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +        <img class="promo__image" src="img/promo-mobile.jpg" width="260" height="315" alt="Корзинки">
поправь альт на более "описательное" описание, и точку в конце

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +        <img class="promo__image" src="img/promo-mobile.jpg" width="260" height="315" alt="Корзинки">
а да, и чего он в самом конце блока идет, когда под ним еще `<p>` и `<a>`?

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +      <div class="about__wrapper">
див лишний

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +        <ul class="about__list">
самостоятельный блок

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +        <ul class="about__list">
ul-ки вообще всегда самостоятельные блоки

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +      <div class="reviews__wrapper">
лишний див

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +    <section class="reviews slider">
нет  смысла делать 2 блока из одного блока. У тебя есть ещё на сайте слайдеры? Или ревью?

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +        <h2 class="reviews__title">Отзывы клиентов</h2>
```suggestion
        <h2 class="reviews__title">Отзывы</h2>
```

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +          <p class="review__user-link">@misssssiskras</p>
blockquote не хочешь использовать?

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +      <div class="contacts__wrapper">
лишний див. Уже всё обернула, зачем еще один тег-обертка?

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +          <img class="contacts__map--image" src="img/map-mobile.jpg" alt="ул. Большая Конюшенная, 19/8">
поправь альт на пустоту, тк нет смысла дублировать инфу, которую только что скрин-ридер прочитал из dd адреса

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +    <div class="page-footer__wrapper">
уже всё обернула в тег footer - лишний див

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +      <div class="page-footer_social social">
лишний див

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +        <ul class="social__list">
самостоятельный блок

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +        <b class="copyright__text">Разработано:</b>
нет смысла использовать презентационные теги в не пользовательском контенте, тк у тебя есть цсс, чтобы задать стили.

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +          <span class="visually-hidden">Логотип HTML Academy</span>
Нужна "слепому" человеку информация, что это картинка логотип академии? Нет, не нужна

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +          <span class="visually-hidden">Логотип HTML Academy</span>
тем более свг вполне себе дополняется тегами доступности - что тебе и нужно добавить.

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +        <legend class="popup__legend">Выберите размер:</legend>
всё, что внутри формы - всегда относится к блоку формы.

2021-08-01 20:17 UTC, Manyaka commented on source/index.html
> +        <legend class="popup__legend">Выберите размер:</legend>
ниже поправь всё, ну кроме ul - который самостоятельный блок

2021-08-02 18:34 UTC, IreneMMM commented on source/index.html
> +            <a href="form.html">Вязание на заказ
у меня VS code, вроде всегда нажимаю "форматировать". Но на всякий случай установила расширение Beautify.
А что было криво?)

2021-08-02 18:52 UTC, Manyaka commented on source/index.html
> +            <a href="form.html">Вязание на заказ
```
          <li class="site-list__item">
            <a href="catalog.html">
              Каталог товаров
            </a>
          </li>
          <li class="site-list__item">
            <a href="form.html">Вязание на заказ
            </a>
          </li>
```

это кривовато

2021-08-02 19:12 UTC, IreneMMM commented on source/index.html
> +      <img src="img/logo-mobile.svg" width="86" height="35" alt="Логотип сайта Мишка»">
функциональный думаю, переделала на  alt="Перейти на главную страница сайта Мишка."

2021-08-02 19:31 UTC, Manyaka commented on source/index.html
> +      <img src="img/logo-mobile.svg" width="86" height="35" alt="Логотип сайта Мишка»">
Да, такой альт, только именно так дословно - это альт внутренних страниц, а на главной просто указание, что вы на главной: "главная страница сайта по продаже вязанных вещей Мишка."

2021-08-02 20:52 UTC, IreneMMM commented on source/index.html
> +              </svg>
если я правильно думаю - декоративные, их можно пока убрать, потом вставить через <use xlink...>. тогда на них можно и hover использовать

2021-08-02 21:38 UTC, IreneMMM commented on source/index.html
> +              <img src="img/lamp.png" width="40" height="62" alt="Иконка блока предметы интерьера">
декоративная, добавлю через CSS

2021-08-02 21:44 UTC, IreneMMM commented on source/index.html
> +        <h2 class="promo__title">Вязаные корзинки</h2>
так учили на лайве и в разметке Барбершопа) сначала секция, потом див, внутри h2.

2021-08-03 03:50 UTC, IreneMMM commented on source/img/logo-mobile.svg
> +<svg width="86" height="35" viewBox="0 0 86 35" fill="none" xmlns="http://www.w3.org/2000/svg">
футер лого у мпня вставлен инлайн, переделать?

2021-08-03 03:54 UTC, IreneMMM commented on source/index.html
> +        <ul class="categories__list">
не совсем понятно с этими ul и wrapper. Если убрать отдельный див для wrapper, wrapper нужно повесить на ul или он вообще не нужен, но как тогда центрировать контент? 
Если делать ul отдельным блоком - нужно отдельное название или типа <ul class="categories__list categories-list>?
или categories__list вообще убрать?

2021-08-03 04:04 UTC, IreneMMM commented on source/index.html
> +          <span class="visually-hidden">Логотип HTML Academy</span>
если добавить вместо span -  <title id="title">Перейти на страницу Онлайн‑курса HTML и CSS. Адаптивная вёрстка и автоматизация</title>

2021-08-03 04:43 UTC, Manyaka commented on source/index.html
> +              </svg>
да, если ты не сможешь через бекграунд их менять, то в таком случае, это будет спрайт-свг, убери пока, потом вставишь

2021-08-03 04:52 UTC, Manyaka commented on source/index.html
> +        <h2 class="promo__title">Вязаные корзинки</h2>
да я уже посмотрела демки.  Всё равно убирай дивы, они не имеют смысла, тк есть секшен, или убирай секшен, мне без разницы, тут дело предпочтений. Секшен, конечно, более семантический тег, он более говорящий. Что имеет значение - это не плодить теги без необходимости, тк они влияют на скорость отрисовки страницы, и у них есть предельное количество на страницу (но чёто я не нашла этого количества в инете, может ты встречала упоминание?) где-то в районе 10 тыщ тегов, но поверь мне, это легко достигается, когда начинаешь плодить фреймворки, которые каждый чих оборачивают в див :))))

2021-08-03 04:54 UTC, Manyaka commented on source/img/logo-mobile.svg
> +<svg width="86" height="35" viewBox="0 0 86 35" fill="none" xmlns="http://www.w3.org/2000/svg">
если он там инлайн, то отсюда удали, зачем дублировать? Но лучше оставь и сделай потом спрайт свг, для этого нужны будут тут свегешки, чтобы их собрать в спрайт.

2021-08-03 04:57 UTC, Manyaka commented on source/index.html
> +        <ul class="categories__list">
Центрировать ul, как элемент категорий. Это так называемое миксование в беме, когда блок, одновременно и чей-то элемент. categories__list - по этому классу центрируешь, тк центрирование - это не характеристика самостоятельного блока, а он центрируется, только когда элемент категорий. И categories-list - на этот класс вешаешь все свойства, которые описывают его как самостоятельный блок

2021-08-03 04:57 UTC, Manyaka commented on source/index.html
> +          <span class="visually-hidden">Логотип HTML Academy</span>
да, в правильном направлении читаешь.

2021-08-04 06:06 UTC, Manyaka requested changes

2021-08-04 06:06 UTC, Manyaka commented on source/index.html
> +        <svg class="copyright__logo" width="27" height="35" viewBox="0 0 27 35" fill="none">
```suggestion
        <svg class="copyright__logo" width="27" height="35" viewBox="0 0 27 35" fill="none" aria-labelledby="title">
```
это надо же сказать, что свг описывается этим тайтлом с этим id

2021-08-04 06:06 UTC, Manyaka commented on source/index.html
> +      <button class="main-nav__toggle" type="button"><span class="visually-hidden">Открыть меню</span></button>
```suggestion
      <button class="main-nav__toggle" type="button"><span class="visually-hidden">Открыть меню.</span></button>
```

Просто запомни, что скрин-ридер такая штука, которая не человек, ей воздух не нужен, чтобы говорить, поэтому он читает всё подряд без пауз. Чтобы сделать паузу - он должен видеть точку. Поэтому всё, что мы делаем для скрин-ридера на сайте - должно быть с точкой, чтобы он прочитал это как отдельное предложение.

2021-08-04 06:06 UTC, Manyaka commented on source/index.html
> +        <ul class="popup-list">
это не попап лист (список), это список размеров. Надо отразить это в названии класса блока

2021-08-04 06:06 UTC, Manyaka commented on source/index.html
> +        <ul class="main-nav__list menu-list">
Меню-лист - очень удачно подобрала название блока!

2021-08-05 11:19 UTC, Manyaka requested changes

2021-08-05 11:19 UTC, Manyaka commented on source/index.html
> +            <label class="size-list__label" for="size-s">S</label>
```suggestion
            <input class="size-table__input" id="size-s" type="radio" name="item-size" value="s">
            <label class="size-table__label" for="size-s">S</label>
```

наговорю тебе на телегу голосом, а то писать долго

2021-08-05 19:10 UTC, merged